stages:
- build
- test
- checkstyle
- pmd
- deploy

variables:
  MAVEN_OPTS: "-Dmaven.test.failure.ignore=true"

before_script:
  - 'export MAVEN_OPTS="-Xmx2g -Xms512m"'
  - 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
  - 'export PATH=$JAVA_HOME/bin:$PATH'

build:
  stage: build
  image: maven:3.8.4-openjdk-11
  script:
    - mvn clean install -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour
  only:
    - branches
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:
  stage: test
  image: maven:3.8.4-openjdk-11
  script:
    - mvn test
  artifacts:
    when: always
    reports:
      junit: target/test-classes/*.xml
  only:
    - branches

checkstyle:
  stage: checkstyle
  image: maven:3.8.4-openjdk-11
  script:
    - mvn checkstyle:check
  allow_failure: true
  only:
    - branches
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

pmd:
  stage: pmd
  image: maven:3.8.4-openjdk-11
  script:
    - mvn pmd:check
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH =~ /^feature-/'

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
  only:
    - main

merge_check:
  stage: test
  script:
    - mvn test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'