stages:
  - build
  - test
  - checkstyle
  - pmd
  - deploy

variables:
  MAVEN_OPTS: "-Xmx2g -Xms512m"

before_script:
  - 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
  - 'export PATH=$JAVA_HOME/bin:$PATH'

build:
  stage: build
  image: maven:3.8.4-openjdk-11
  script:
    - echo "Starting Build Stage"
    - mvn clean install -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:
  stage: test
  image: maven:3.8.4-openjdk-11
  script:
    - echo "Running Tests"
    - mvn clean test -e
  artifacts:
    when: always
    paths:
      - target/site/jacoco/index.html
      - target/jacoco-coverage-report.xml
    reports:
      junit: target/test-classes/*.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

checkstyle:
  stage: checkstyle
  image: maven:3.8.4-openjdk-11
  script:
    - echo "Running Checkstyle"
    - mvn checkstyle:check
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

pmd:
  stage: pmd
  image: maven:3.8.4-openjdk-11
  script:
    - echo "Running PMD"
    - mvn pmd:check
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH =~ /^feature-/'

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
