name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - feature-*
  pull_request:
    branches:
      - main
      - dev

env:
  MAVEN_OPTS: "-Dmaven.test.failure.ignore=true"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.4-openjdk-11
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Maven Options
        run: |
          export MAVEN_OPTS="-Xmx2g -Xms512m"
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jar-files
          path: target/*.jar
          retention-days: 1

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.8.4-openjdk-11
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: mvn clean test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            target/site/jacoco/index.html
            target/jacoco-coverage-report.xml
            target/test-classes/*.xml

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.8.4-openjdk-11
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Checkstyle
        run: mvn checkstyle:check

    continue-on-error: true

  pmd:
    name: PMD Analysis
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.8.4-openjdk-11
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run PMD
        run: mvn pmd:check

    continue-on-error: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production
        run: echo "Deploying to production"
